spring.application.name=email-writer-sb

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent?key=

gemini.api.key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


server.port=8080

# Logging Configuration
logging.level.com.email.writer=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG
